<?php

namespace Proxies\__CG__\Incentives\CatalogoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Programa extends \Incentives\CatalogoBundle\Entity\Programa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'id', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'nombre', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'descripcion', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'fechainicio', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'fechafin', 'estado', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'logistica', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'iva', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'diasentrega', 'cliente', 'catalogo', 'ordenesproducto', 'presupuestos', 'factura', 'solicitud', 'participantes', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'centrocostos', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'fechaModificacion', 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'id', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'nombre', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'descripcion', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'fechainicio', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'fechafin', 'estado', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'logistica', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'iva', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'diasentrega', 'cliente', 'catalogo', 'ordenesproducto', 'presupuestos', 'factura', 'solicitud', 'participantes', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'centrocostos', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Programa' . "\0" . 'fechaModificacion', 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Programa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', [$fechainicio]);

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', []);

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafin($fechafin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafin', [$fechafin]);

        return parent::setFechafin($fechafin);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafin', []);

        return parent::getFechafin();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogistica($logistica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogistica', [$logistica]);

        return parent::setLogistica($logistica);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogistica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogistica', []);

        return parent::getLogistica();
    }

    /**
     * {@inheritDoc}
     */
    public function setIva($iva)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIva', [$iva]);

        return parent::setIva($iva);
    }

    /**
     * {@inheritDoc}
     */
    public function getIva()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIva', []);

        return parent::getIva();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasentrega($diasentrega)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasentrega', [$diasentrega]);

        return parent::setDiasentrega($diasentrega);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasentrega()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasentrega', []);

        return parent::getDiasentrega();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentrocostos($centrocostos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentrocostos', [$centrocostos]);

        return parent::setCentrocostos($centrocostos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentrocostos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentrocostos', []);

        return parent::getCentrocostos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(\Incentives\CatalogoBundle\Entity\Estados $estado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\Incentives\CatalogoBundle\Entity\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function addCatalogo(\Incentives\CatalogoBundle\Entity\Catalogos $catalogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCatalogo', [$catalogo]);

        return parent::addCatalogo($catalogo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCatalogo(\Incentives\CatalogoBundle\Entity\Catalogos $catalogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCatalogo', [$catalogo]);

        return parent::removeCatalogo($catalogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCatalogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatalogo', []);

        return parent::getCatalogo();
    }

    /**
     * {@inheritDoc}
     */
    public function addPresupuesto(\Incentives\FacturacionBundle\Entity\Presupuestos $presupuestos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPresupuesto', [$presupuestos]);

        return parent::addPresupuesto($presupuestos);
    }

    /**
     * {@inheritDoc}
     */
    public function removePresupuesto(\Incentives\FacturacionBundle\Entity\Presupuestos $presupuestos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePresupuesto', [$presupuestos]);

        return parent::removePresupuesto($presupuestos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresupuestos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresupuestos', []);

        return parent::getPresupuestos();
    }

    /**
     * {@inheritDoc}
     */
    public function addFactura(\Incentives\FacturacionBundle\Entity\Factura $factura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFactura', [$factura]);

        return parent::addFactura($factura);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFactura(\Incentives\FacturacionBundle\Entity\Factura $factura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFactura', [$factura]);

        return parent::removeFactura($factura);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactura', []);

        return parent::getFactura();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolicitud(\Incentives\SolicitudesBundle\Entity\Solicitud $solicitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolicitud', [$solicitud]);

        return parent::addSolicitud($solicitud);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolicitud(\Incentives\SolicitudesBundle\Entity\Solicitud $solicitud)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolicitud', [$solicitud]);

        return parent::removeSolicitud($solicitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitud', []);

        return parent::getSolicitud();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipante(\Incentives\RedencionesBundle\Entity\Participantes $participantes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipante', [$participantes]);

        return parent::addParticipante($participantes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParticipante(\Incentives\RedencionesBundle\Entity\Participantes $participantes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParticipante', [$participantes]);

        return parent::removeParticipante($participantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipantes', []);

        return parent::getParticipantes();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdenesproducto(\Incentives\OrdenesBundle\Entity\OrdenesProducto $ordenesproducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdenesproducto', [$ordenesproducto]);

        return parent::addOrdenesproducto($ordenesproducto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdenesproducto(\Incentives\OrdenesBundle\Entity\OrdenesProducto $ordenesproducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdenesproducto', [$ordenesproducto]);

        return parent::removeOrdenesproducto($ordenesproducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenesproducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenesproducto', []);

        return parent::getOrdenesproducto();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCC', []);

        return parent::getNombreCC();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModificacion($fechaModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModificacion', [$fechaModificacion]);

        return parent::setFechaModificacion($fechaModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModificacion', []);

        return parent::getFechaModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Incentives\BaseBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

}
