<?php

namespace Proxies\__CG__\Incentives\CatalogoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cliente extends \Incentives\CatalogoBundle\Entity\Cliente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'nombre', 'tipodocumento', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'numero_documento', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'direccion', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'telefono', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'correo', 'estado', 'programa', 'usuarios', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'fechaModificacion', 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'id', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'nombre', 'tipodocumento', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'numero_documento', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'direccion', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'telefono', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'correo', 'estado', 'programa', 'usuarios', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Cliente' . "\0" . 'fechaModificacion', 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cliente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setCorreo($correo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCorreo', [$correo]);

        return parent::setCorreo($correo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCorreo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCorreo', []);

        return parent::getCorreo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroDocumento($numeroDocumento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroDocumento', [$numeroDocumento]);

        return parent::setNumeroDocumento($numeroDocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroDocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroDocumento', []);

        return parent::getNumeroDocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipodocumento(\Incentives\OperacionesBundle\Entity\Tipodocumento $tipodocumento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipodocumento', [$tipodocumento]);

        return parent::setTipodocumento($tipodocumento);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipodocumento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipodocumento', []);

        return parent::getTipodocumento();
    }

    /**
     * {@inheritDoc}
     */
    public function addProgramon(\Incentives\CatalogoBundle\Entity\Programa $programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProgramon', [$programa]);

        return parent::addProgramon($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProgramon(\Incentives\CatalogoBundle\Entity\Programa $programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProgramon', [$programa]);

        return parent::removeProgramon($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrograma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrograma', []);

        return parent::getPrograma();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrograma(\Incentives\CatalogoBundle\Entity\Programa $programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrograma', [$programa]);

        return parent::addPrograma($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrograma(\Incentives\CatalogoBundle\Entity\Programa $programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrograma', [$programa]);

        return parent::removePrograma($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado(\Incentives\CatalogoBundle\Entity\Estados $estado = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModificacion($fechaModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModificacion', [$fechaModificacion]);

        return parent::setFechaModificacion($fechaModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModificacion', []);

        return parent::getFechaModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Incentives\BaseBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuario(\Incentives\BaseBundle\Entity\Usuario $usuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuario', [$usuarios]);

        return parent::addUsuario($usuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuario(\Incentives\BaseBundle\Entity\Usuario $usuarios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuario', [$usuarios]);

        return parent::removeUsuario($usuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarios', []);

        return parent::getUsuarios();
    }

}
