<?php

namespace Proxies\__CG__\Incentives\CatalogoBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Producto extends \Incentives\CatalogoBundle\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setReferencia($referencia)
    {
        $this->__load();
        return parent::setReferencia($referencia);
    }

    public function getReferencia()
    {
        $this->__load();
        return parent::getReferencia();
    }

    public function setMarca($marca)
    {
        $this->__load();
        return parent::setMarca($marca);
    }

    public function getMarca()
    {
        $this->__load();
        return parent::getMarca();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setCodEAN($codEAN)
    {
        $this->__load();
        return parent::setCodEAN($codEAN);
    }

    public function getCodEAN()
    {
        $this->__load();
        return parent::getCodEAN();
    }

    public function setCodInc($codInc)
    {
        $this->__load();
        return parent::setCodInc($codInc);
    }

    public function getCodInc()
    {
        $this->__load();
        return parent::getCodInc();
    }

    public function setAlto($alto)
    {
        $this->__load();
        return parent::setAlto($alto);
    }

    public function getAlto()
    {
        $this->__load();
        return parent::getAlto();
    }

    public function setLargo($largo)
    {
        $this->__load();
        return parent::setLargo($largo);
    }

    public function getLargo()
    {
        $this->__load();
        return parent::getLargo();
    }

    public function setAncho($ancho)
    {
        $this->__load();
        return parent::setAncho($ancho);
    }

    public function getAncho()
    {
        $this->__load();
        return parent::getAncho();
    }

    public function setPeso($peso)
    {
        $this->__load();
        return parent::setPeso($peso);
    }

    public function getPeso()
    {
        $this->__load();
        return parent::getPeso();
    }

    public function setCategoria(\Incentives\OperacionesBundle\Entity\Categoria $categoria = NULL)
    {
        $this->__load();
        return parent::setCategoria($categoria);
    }

    public function getCategoria()
    {
        $this->__load();
        return parent::getCategoria();
    }

    public function addImagenproducto(\Incentives\CatalogoBundle\Entity\Imagenproducto $imagenproducto)
    {
        $this->__load();
        return parent::addImagenproducto($imagenproducto);
    }

    public function removeImagenproducto(\Incentives\CatalogoBundle\Entity\Imagenproducto $imagenproducto)
    {
        $this->__load();
        return parent::removeImagenproducto($imagenproducto);
    }

    public function getImagenproducto()
    {
        $this->__load();
        return parent::getImagenproducto();
    }

    public function setIva($iva)
    {
        $this->__load();
        return parent::setIva($iva);
    }

    public function getIva()
    {
        $this->__load();
        return parent::getIva();
    }

    public function setFechacreacion($fechacreacion)
    {
        $this->__load();
        return parent::setFechacreacion($fechacreacion);
    }

    public function getFechacreacion()
    {
        $this->__load();
        return parent::getFechacreacion();
    }

    public function setFechaactualizacion($fechaactualizacion)
    {
        $this->__load();
        return parent::setFechaactualizacion($fechaactualizacion);
    }

    public function getFechaactualizacion()
    {
        $this->__load();
        return parent::getFechaactualizacion();
    }

    public function addProductoprecio(\Incentives\CatalogoBundle\Entity\Productoprecio $productoprecio)
    {
        $this->__load();
        return parent::addProductoprecio($productoprecio);
    }

    public function removeProductoprecio(\Incentives\CatalogoBundle\Entity\Productoprecio $productoprecio)
    {
        $this->__load();
        return parent::removeProductoprecio($productoprecio);
    }

    public function getProductoprecio()
    {
        $this->__load();
        return parent::getProductoprecio();
    }

    public function addProductocatalogo(\Incentives\CatalogoBundle\Entity\Productocatalogo $productocatalogo)
    {
        $this->__load();
        return parent::addProductocatalogo($productocatalogo);
    }

    public function removeProductocatalogo(\Incentives\CatalogoBundle\Entity\Productocatalogo $productocatalogo)
    {
        $this->__load();
        return parent::removeProductocatalogo($productocatalogo);
    }

    public function getProductocatalogo()
    {
        $this->__load();
        return parent::getProductocatalogo();
    }

    public function addOrdenesproducto(\Incentives\OrdenesBundle\Entity\OrdenesProducto $ordenesproducto)
    {
        $this->__load();
        return parent::addOrdenesproducto($ordenesproducto);
    }

    public function removeOrdenesproducto(\Incentives\OrdenesBundle\Entity\OrdenesProducto $ordenesproducto)
    {
        $this->__load();
        return parent::removeOrdenesproducto($ordenesproducto);
    }

    public function getOrdenesproducto()
    {
        $this->__load();
        return parent::getOrdenesproducto();
    }

    public function setEstadoIva($estadoIva)
    {
        $this->__load();
        return parent::setEstadoIva($estadoIva);
    }

    public function getEstadoIva()
    {
        $this->__load();
        return parent::getEstadoIva();
    }

    public function setLogistica($logistica)
    {
        $this->__load();
        return parent::setLogistica($logistica);
    }

    public function getLogistica()
    {
        $this->__load();
        return parent::getLogistica();
    }

    public function setIncremento($incremento)
    {
        $this->__load();
        return parent::setIncremento($incremento);
    }

    public function getIncremento()
    {
        $this->__load();
        return parent::getIncremento();
    }

    public function setProductoclasificacion(\Incentives\CatalogoBundle\Entity\Productoclasificacion $productoclasificacion = NULL)
    {
        $this->__load();
        return parent::setProductoclasificacion($productoclasificacion);
    }

    public function getProductoclasificacion()
    {
        $this->__load();
        return parent::getProductoclasificacion();
    }

    public function addInventario(\Incentives\InventarioBundle\Entity\Inventario $inventario)
    {
        $this->__load();
        return parent::addInventario($inventario);
    }

    public function removeInventario(\Incentives\InventarioBundle\Entity\Inventario $inventario)
    {
        $this->__load();
        return parent::removeInventario($inventario);
    }

    public function getInventario()
    {
        $this->__load();
        return parent::getInventario();
    }

    public function addAtributo(\Incentives\CatalogoBundle\Entity\Atributosproducto $atributos)
    {
        $this->__load();
        return parent::addAtributo($atributos);
    }

    public function removeAtributo(\Incentives\CatalogoBundle\Entity\Atributosproducto $atributos)
    {
        $this->__load();
        return parent::removeAtributo($atributos);
    }

    public function getAtributos()
    {
        $this->__load();
        return parent::getAtributos();
    }

    public function addCalificacion(\Incentives\CatalogoBundle\Entity\ProductoCalificacion $calificacion)
    {
        $this->__load();
        return parent::addCalificacion($calificacion);
    }

    public function removeCalificacion(\Incentives\CatalogoBundle\Entity\ProductoCalificacion $calificacion)
    {
        $this->__load();
        return parent::removeCalificacion($calificacion);
    }

    public function getCalificacion()
    {
        $this->__load();
        return parent::getCalificacion();
    }

    public function addProductoidioma(\Incentives\CatalogoBundle\Entity\ProductoIdiomas $productoidioma)
    {
        $this->__load();
        return parent::addProductoidioma($productoidioma);
    }

    public function removeProductoidioma(\Incentives\CatalogoBundle\Entity\ProductoIdiomas $productoidioma)
    {
        $this->__load();
        return parent::removeProductoidioma($productoidioma);
    }

    public function getProductoidioma()
    {
        $this->__load();
        return parent::getProductoidioma();
    }

    public function setEstado(\Incentives\CatalogoBundle\Entity\Estados $estado = NULL)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setEanTemp($eanTemp)
    {
        $this->__load();
        return parent::setEanTemp($eanTemp);
    }

    public function getEanTemp()
    {
        $this->__load();
        return parent::getEanTemp();
    }

    public function setCodImg($codImg)
    {
        $this->__load();
        return parent::setCodImg($codImg);
    }

    public function getCodImg()
    {
        $this->__load();
        return parent::getCodImg();
    }

    public function getLabel()
    {
        $this->__load();
        return parent::getLabel();
    }

    public function getNombreId()
    {
        $this->__load();
        return parent::getNombreId();
    }

    public function addCotizacionproducto(\Incentives\SolicitudesBundle\Entity\CotizacionProducto $cotizacionproducto)
    {
        $this->__load();
        return parent::addCotizacionproducto($cotizacionproducto);
    }

    public function removeCotizacionproducto(\Incentives\SolicitudesBundle\Entity\CotizacionProducto $cotizacionproducto)
    {
        $this->__load();
        return parent::removeCotizacionproducto($cotizacionproducto);
    }

    public function getCotizacionproducto()
    {
        $this->__load();
        return parent::getCotizacionproducto();
    }

    public function setTipo(\Incentives\CatalogoBundle\Entity\ProductoTipo $tipo = NULL)
    {
        $this->__load();
        return parent::setTipo($tipo);
    }

    public function getTipo()
    {
        $this->__load();
        return parent::getTipo();
    }

    public function addFacturaproducto(\Incentives\FacturacionBundle\Entity\FacturaProductos $facturaproductos)
    {
        $this->__load();
        return parent::addFacturaproducto($facturaproductos);
    }

    public function removeFacturaproducto(\Incentives\FacturacionBundle\Entity\FacturaProductos $facturaproductos)
    {
        $this->__load();
        return parent::removeFacturaproducto($facturaproductos);
    }

    public function getFacturaproductos()
    {
        $this->__load();
        return parent::getFacturaproductos();
    }

    public function setFechaModificacion($fechaModificacion)
    {
        $this->__load();
        return parent::setFechaModificacion($fechaModificacion);
    }

    public function getFechaModificacion()
    {
        $this->__load();
        return parent::getFechaModificacion();
    }

    public function setUsuario(\Incentives\BaseBundle\Entity\Usuario $usuario = NULL)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'referencia', 'marca', 'descripcion', 'codEAN', 'eanTemp', 'codInc', 'alto', 'largo', 'ancho', 'peso', 'iva', 'estadoIva', 'logistica', 'incremento', 'fechacreacion', 'fechaactualizacion', 'codImg', 'fechaModificacion', 'categoria', 'estado', 'tipo', 'imagenproducto', 'productoprecio', 'productocatalogo', 'facturaproductos', 'ordenesproducto', 'cotizacionproducto', 'productoclasificacion', 'inventario', 'atributos', 'calificacion', 'productoidioma', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}