<?php

namespace Proxies\__CG__\Incentives\CatalogoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Estados extends \Incentives\CatalogoBundle\Entity\Estados implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Estados' . "\0" . 'id', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Estados' . "\0" . 'nombre', 'cliente', 'programa', 'producto', 'productoprecio', 'atributos', 'proveedor', 'catalogo', 'ordenesproducto', 'solicitudasignar', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Estados' . "\0" . 'fechaModificacion', 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Estados' . "\0" . 'id', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Estados' . "\0" . 'nombre', 'cliente', 'programa', 'producto', 'productoprecio', 'atributos', 'proveedor', 'catalogo', 'ordenesproducto', 'solicitudasignar', '' . "\0" . 'Incentives\\CatalogoBundle\\Entity\\Estados' . "\0" . 'fechaModificacion', 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Estados $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function addCatalogo(\Incentives\CatalogoBundle\Entity\Catalogos $catalogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCatalogo', [$catalogo]);

        return parent::addCatalogo($catalogo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCatalogo(\Incentives\CatalogoBundle\Entity\Catalogos $catalogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCatalogo', [$catalogo]);

        return parent::removeCatalogo($catalogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCatalogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatalogo', []);

        return parent::getCatalogo();
    }

    /**
     * {@inheritDoc}
     */
    public function addProducto(\Incentives\CatalogoBundle\Entity\Producto $producto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProducto', [$producto]);

        return parent::addProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProducto(\Incentives\CatalogoBundle\Entity\Producto $producto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProducto', [$producto]);

        return parent::removeProducto($producto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducto', []);

        return parent::getProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductoprecio(\Incentives\CatalogoBundle\Entity\Productoprecio $productoprecio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductoprecio', [$productoprecio]);

        return parent::addProductoprecio($productoprecio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductoprecio(\Incentives\CatalogoBundle\Entity\Productoprecio $productoprecio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductoprecio', [$productoprecio]);

        return parent::removeProductoprecio($productoprecio);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoprecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoprecio', []);

        return parent::getProductoprecio();
    }

    /**
     * {@inheritDoc}
     */
    public function addAtributo(\Incentives\CatalogoBundle\Entity\Atributosproducto $atributos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAtributo', [$atributos]);

        return parent::addAtributo($atributos);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAtributo(\Incentives\CatalogoBundle\Entity\Atributosproducto $atributos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAtributo', [$atributos]);

        return parent::removeAtributo($atributos);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributos', []);

        return parent::getAtributos();
    }

    /**
     * {@inheritDoc}
     */
    public function addCliente(\Incentives\CatalogoBundle\Entity\Cliente $cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCliente', [$cliente]);

        return parent::addCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCliente(\Incentives\CatalogoBundle\Entity\Cliente $cliente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCliente', [$cliente]);

        return parent::removeCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrograma(\Incentives\CatalogoBundle\Entity\Programa $programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrograma', [$programa]);

        return parent::addPrograma($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrograma(\Incentives\CatalogoBundle\Entity\Programa $programa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrograma', [$programa]);

        return parent::removePrograma($programa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrograma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrograma', []);

        return parent::getPrograma();
    }

    /**
     * {@inheritDoc}
     */
    public function addProveedor(\Incentives\OperacionesBundle\Entity\Proveedores $proveedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProveedor', [$proveedor]);

        return parent::addProveedor($proveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProveedor(\Incentives\OperacionesBundle\Entity\Proveedores $proveedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProveedor', [$proveedor]);

        return parent::removeProveedor($proveedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getProveedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProveedor', []);

        return parent::getProveedor();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdenesproducto(\Incentives\OrdenesBundle\Entity\OrdenesProducto $ordenesproducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdenesproducto', [$ordenesproducto]);

        return parent::addOrdenesproducto($ordenesproducto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdenesproducto(\Incentives\OrdenesBundle\Entity\OrdenesProducto $ordenesproducto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdenesproducto', [$ordenesproducto]);

        return parent::removeOrdenesproducto($ordenesproducto);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenesproducto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenesproducto', []);

        return parent::getOrdenesproducto();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolicitudasignar(\Incentives\SolicitudesBundle\Entity\SolicitudesAsignar $solicitudasignar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolicitudasignar', [$solicitudasignar]);

        return parent::addSolicitudasignar($solicitudasignar);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolicitudasignar(\Incentives\SolicitudesBundle\Entity\SolicitudesAsignar $solicitudasignar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolicitudasignar', [$solicitudasignar]);

        return parent::removeSolicitudasignar($solicitudasignar);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudasignar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudasignar', []);

        return parent::getSolicitudasignar();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModificacion($fechaModificacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModificacion', [$fechaModificacion]);

        return parent::setFechaModificacion($fechaModificacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModificacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModificacion', []);

        return parent::getFechaModificacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario(\Incentives\BaseBundle\Entity\Usuario $usuario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

}
