<?php

namespace Proxies\__CG__\Incentives\FacturacionBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class FacturaProductos extends \Incentives\FacturacionBundle\Entity\FacturaProductos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCantidad($cantidad)
    {
        $this->__load();
        return parent::setCantidad($cantidad);
    }

    public function getCantidad()
    {
        $this->__load();
        return parent::getCantidad();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setValorUnitario($valorUnitario)
    {
        $this->__load();
        return parent::setValorUnitario($valorUnitario);
    }

    public function getValorUnitario()
    {
        $this->__load();
        return parent::getValorUnitario();
    }

    public function setValorTotal($valorTotal)
    {
        $this->__load();
        return parent::setValorTotal($valorTotal);
    }

    public function getValorTotal()
    {
        $this->__load();
        return parent::getValorTotal();
    }

    public function setFactura(\Incentives\FacturacionBundle\Entity\Factura $factura = NULL)
    {
        $this->__load();
        return parent::setFactura($factura);
    }

    public function getFactura()
    {
        $this->__load();
        return parent::getFactura();
    }

    public function setProducto(\Incentives\CatalogoBundle\Entity\Producto $producto = NULL)
    {
        $this->__load();
        return parent::setProducto($producto);
    }

    public function getProducto()
    {
        $this->__load();
        return parent::getProducto();
    }

    public function setFechaModificacion($fechaModificacion)
    {
        $this->__load();
        return parent::setFechaModificacion($fechaModificacion);
    }

    public function getFechaModificacion()
    {
        $this->__load();
        return parent::getFechaModificacion();
    }

    public function setUsuario(\Incentives\BaseBundle\Entity\Usuario $usuario = NULL)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function addRedencione(\Incentives\RedencionesBundle\Entity\Redenciones $redenciones)
    {
        $this->__load();
        return parent::addRedencione($redenciones);
    }

    public function removeRedencione(\Incentives\RedencionesBundle\Entity\Redenciones $redenciones)
    {
        $this->__load();
        return parent::removeRedencione($redenciones);
    }

    public function getRedenciones()
    {
        $this->__load();
        return parent::getRedenciones();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'cantidad', 'descripcion', 'valorUnitario', 'valorTotal', 'fechaModificacion', 'producto', 'factura', 'redenciones', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}