<?php

namespace Proxies\__CG__\Incentives\OrdenesBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class OrdenesProducto extends \Incentives\OrdenesBundle\Entity\OrdenesProducto implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCantidad($cantidad)
    {
        $this->__load();
        return parent::setCantidad($cantidad);
    }

    public function getCantidad()
    {
        $this->__load();
        return parent::getCantidad();
    }

    public function setCantidadrecibida($cantidadrecibida)
    {
        $this->__load();
        return parent::setCantidadrecibida($cantidadrecibida);
    }

    public function getCantidadrecibida()
    {
        $this->__load();
        return parent::getCantidadrecibida();
    }

    public function setValorunidad($valorunidad)
    {
        $this->__load();
        return parent::setValorunidad($valorunidad);
    }

    public function getValorunidad()
    {
        $this->__load();
        return parent::getValorunidad();
    }

    public function setValortotal($valortotal)
    {
        $this->__load();
        return parent::setValortotal($valortotal);
    }

    public function getValortotal()
    {
        $this->__load();
        return parent::getValortotal();
    }

    public function setProducto(\Incentives\CatalogoBundle\Entity\Producto $producto = NULL)
    {
        $this->__load();
        return parent::setProducto($producto);
    }

    public function getProducto()
    {
        $this->__load();
        return parent::getProducto();
    }

    public function setOrdenesCompra(\Incentives\OrdenesBundle\Entity\OrdenesCompra $ordenesCompra = NULL)
    {
        $this->__load();
        return parent::setOrdenesCompra($ordenesCompra);
    }

    public function getOrdenesCompra()
    {
        $this->__load();
        return parent::getOrdenesCompra();
    }

    public function addGuiaEnvio(\Incentives\RedencionesBundle\Entity\GuiaEnvio $guiaEnvio)
    {
        $this->__load();
        return parent::addGuiaEnvio($guiaEnvio);
    }

    public function removeGuiaEnvio(\Incentives\RedencionesBundle\Entity\GuiaEnvio $guiaEnvio)
    {
        $this->__load();
        return parent::removeGuiaEnvio($guiaEnvio);
    }

    public function getGuiaEnvio()
    {
        $this->__load();
        return parent::getGuiaEnvio();
    }

    public function addRedencione(\Incentives\RedencionesBundle\Entity\Redenciones $redenciones)
    {
        $this->__load();
        return parent::addRedencione($redenciones);
    }

    public function removeRedencione(\Incentives\RedencionesBundle\Entity\Redenciones $redenciones)
    {
        $this->__load();
        return parent::removeRedencione($redenciones);
    }

    public function getRedenciones()
    {
        $this->__load();
        return parent::getRedenciones();
    }

    public function addOrdenesproductohistorico(\Incentives\OrdenesBundle\Entity\OrdenesProductoHistorico $ordenesproductohistorico)
    {
        $this->__load();
        return parent::addOrdenesproductohistorico($ordenesproductohistorico);
    }

    public function removeOrdenesproductohistorico(\Incentives\OrdenesBundle\Entity\OrdenesProductoHistorico $ordenesproductohistorico)
    {
        $this->__load();
        return parent::removeOrdenesproductohistorico($ordenesproductohistorico);
    }

    public function getOrdenesproductohistorico()
    {
        $this->__load();
        return parent::getOrdenesproductohistorico();
    }

    public function setDescuento($descuento)
    {
        $this->__load();
        return parent::setDescuento($descuento);
    }

    public function getDescuento()
    {
        $this->__load();
        return parent::getDescuento();
    }

    public function addTracking(\Incentives\OrdenesBundle\Entity\Tracking $tracking)
    {
        $this->__load();
        return parent::addTracking($tracking);
    }

    public function removeTracking(\Incentives\OrdenesBundle\Entity\Tracking $tracking)
    {
        $this->__load();
        return parent::removeTracking($tracking);
    }

    public function getTracking()
    {
        $this->__load();
        return parent::getTracking();
    }

    public function setCentrocostos($centrocostos)
    {
        $this->__load();
        return parent::setCentrocostos($centrocostos);
    }

    public function getCentrocostos()
    {
        $this->__load();
        return parent::getCentrocostos();
    }

    public function setEstado(\Incentives\CatalogoBundle\Entity\Estados $estado = NULL)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setPrograma(\Incentives\CatalogoBundle\Entity\Programa $programa = NULL)
    {
        $this->__load();
        return parent::setPrograma($programa);
    }

    public function getPrograma()
    {
        $this->__load();
        return parent::getPrograma();
    }

    public function setIncremento($incremento)
    {
        $this->__load();
        return parent::setIncremento($incremento);
    }

    public function getIncremento()
    {
        $this->__load();
        return parent::getIncremento();
    }

    public function setLogistica($logistica)
    {
        $this->__load();
        return parent::setLogistica($logistica);
    }

    public function getLogistica()
    {
        $this->__load();
        return parent::getLogistica();
    }

    public function addInventario(\Incentives\InventarioBundle\Entity\Inventario $inventario)
    {
        $this->__load();
        return parent::addInventario($inventario);
    }

    public function removeInventario(\Incentives\InventarioBundle\Entity\Inventario $inventario)
    {
        $this->__load();
        return parent::removeInventario($inventario);
    }

    public function getInventario()
    {
        $this->__load();
        return parent::getInventario();
    }

    public function setFechaModificacion($fechaModificacion)
    {
        $this->__load();
        return parent::setFechaModificacion($fechaModificacion);
    }

    public function getFechaModificacion()
    {
        $this->__load();
        return parent::getFechaModificacion();
    }

    public function setUsuario(\Incentives\BaseBundle\Entity\Usuario $usuario = NULL)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function setProductocotizacion(\Incentives\SolicitudesBundle\Entity\CotizacionProducto $productocotizacion = NULL)
    {
        $this->__load();
        return parent::setProductocotizacion($productocotizacion);
    }

    public function getProductocotizacion()
    {
        $this->__load();
        return parent::getProductocotizacion();
    }

    public function setFacturaProducto(\Incentives\FacturacionBundle\Entity\FacturaProductos $facturaProducto = NULL)
    {
        $this->__load();
        return parent::setFacturaProducto($facturaProducto);
    }

    public function getFacturaProducto()
    {
        $this->__load();
        return parent::getFacturaProducto();
    }

    public function setPrecioCliente($precioCliente)
    {
        $this->__load();
        return parent::setPrecioCliente($precioCliente);
    }

    public function getPrecioCliente()
    {
        $this->__load();
        return parent::getPrecioCliente();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'cantidad', 'cantidadrecibida', 'valorunidad', 'valortotal', 'descuento', 'precioCliente', 'incremento', 'logistica', 'centrocostos', 'fechaModificacion', 'guiaEnvio', 'producto', 'ordenesCompra', 'programa', 'productocotizacion', 'estado', 'redenciones', 'ordenesproductohistorico', 'inventario', 'tracking', 'facturaProducto', 'usuario');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}